# Generated by Django 3.0.5 on 2020-04-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('idNo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('exp_time', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
