# Generated by Django 3.0.5 on 2020-05-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('expirationDate', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('expiredStatus', models.IntegerField()),
                ('pantryStatus', models.IntegerField()),
            ],
        ),
    ]
