# Generated by Django 3.0.5 on 2020-05-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pantry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantry',
            name='id',
        ),
        migrations.AddField(
            model_name='pantry',
            name='idNo',
            field=models.CharField(default=0, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grocery',
            name='idNo',
            field=models.CharField(default='0', max_length=255, primary_key=True, serialize=False),
        ),
    ]
