# Generated by Django 3.0.5 on 2020-05-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200502_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantry',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pantry',
            name='idNo',
            field=models.CharField(max_length=255),
        ),
    ]
