# Generated by Django 3.0.5 on 2020-05-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200502_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantry',
            name='idNo',
        ),
    ]
