# Generated by Django 3.0.5 on 2020-05-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200502_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pantry',
            old_name='idNo',
            new_name='pantryId',
        ),
    ]
