# Generated by Django 3.0.5 on 2020-05-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200502_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantry',
            name='pantryId',
        ),
    ]
