# Generated by Django 3.0.5 on 2020-05-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_pantry_pantryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantry',
            name='id',
        ),
        migrations.AddField(
            model_name='pantry',
            name='pantryID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
