# Generated by Django 3.0.5 on 2020-05-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200502_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pantry',
            old_name='pantryID',
            new_name='pantryId',
        ),
    ]
