# Generated by Django 3.0.5 on 2020-05-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200502_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='category',
            new_name='expirationDate',
        ),
        migrations.RenameField(
            model_name='grocery',
            old_name='exp_time',
            new_name='expiredStatus',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='idNo',
        ),
        migrations.AddField(
            model_name='grocery',
            name='groceryId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='grocery',
            name='pantryStatus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocery',
            name='price',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocery',
            name='type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
