# Generated by Django 3.0.5 on 2020-05-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200503_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('expirationDate', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('expiredStatus', models.IntegerField()),
                ('pantryStatus', models.IntegerField()),
                ('month', models.CharField(max_length=255)),
            ],
        ),
    ]
