# Generated by Django 3.0.5 on 2020-05-03 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_trends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trends',
            name='expirationDate',
        ),
    ]
